format = "$all$hostname$character"

[hostname]
ssh_only=false
style="bold dimmed white"
format="[$ssh_symbol$hostname]($style) "

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold dimmed white"
